package main

var tableData = map[string][]string{
	"Info": {
		"version integer default 1",
		"name text",
		"created integer default current_timestamp",
	},
	"Solutions": {
		"uid integer",
		"parent integer",
		"parentType integer",
		"label integer",
		"description text",
		"link text",
		"color integer",
		"border integer",
		"shape integer",
		"x integer",
		"y integer",
		"width integer default 128",
		"height integer default 64",
		"foreign key(parent) references Requirements(id)",
		"foreign key(label) references Labels(id)",
	},
	"Projects": {
		"uid integer",
		"name text",
		"created integer default current_timestamp",
	},
	"ItemVersions": {
		"version integer",
		"item integer",
		"itemV integer default 1",
		"type integer",
		"foreign key (version) references Projects(id)",
	},
	"Requirements": {
		"uid integer",
		"parent integer",
		"parentType integer",
		"label integer",
		"description text",
		"rationale text",
		"fitCriterion text",
		"color integer",
		"border integer",
		"shape integer",
		"x integer",
		"y integer",
		"width integer default 128",
		"height integer default 64",
		"foreign key(parent) references Solutions(id)",
		"foreign key(label) references Labels(id)",
	},
	"LabelItems": {
		"label integer",
		"item integer",
		"type integer",
		"foreign key (label) references Labels(id)",
	},
	"Media": {
		"parent int not null",
		"format text default 'webp'",
		"data blob",
		"foreign key(parent) references Solutions(id)",
	},
	"Labels": {
		"tag text",
		"color integer",
	},
	"ValidationRules": {
		"tag text",
		"enabled integer default 1",
		"data text",
	},
}
